name: Waka Readme

on:
  schedule:
    # Runs at minute 0 every 2 hours (00:00, 02:00, 04:00, etc.).
    - cron: "0 */2 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  update-readme:
    name: Update Readme with Metrics
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_OS: false
          SHOW_PROJECTS: false
          SECTION_NAME: waka
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
